// This file generated by DragoAnt.Extensions.DependencyInjection.Factory source generator

#nullable enable

using DragoAnt.Extensions.DependencyInjection.Example.Models;
using Microsoft.Extensions.DependencyInjection;

namespace NotSetRootNamespace;

/// <summary>
/// Factory dependency injection registration extensions.
/// </summary>
public static class NotSetMethodNameRegistrationExtensions
{
    /// <summary>
    /// NotSetMethodName dependencies and factories registration extension.
    /// </summary>
    /// <remarks>Generated by <a href="https://github.com/DragoAnt/Extensions.DependencyInjection">DragoAnt.Extensions.DependencyInjection</a> source generator.</remarks>
    public static void AddNotSetMethodNameDependencies(this IServiceCollection services)
    {
        services.AddSingleton<HierarchyDepModel>();
        services.AddSingleton<BaseHierarchyDepModel>(p => p.GetRequiredService<HierarchyDepModel>());
        services.AddSingleton<IHierarchyDepModel>(p => p.GetRequiredService<HierarchyDepModel>());
        services.AddScoped<ScopedDepModel>();
        services.AddSingleton<SingletonDepModel>();
        services.AddSingleton<SingletonHierarchyDepModel>();
        services.AddSingleton<BaseHierarchyDepModel>(p => p.GetRequiredService<SingletonHierarchyDepModel>());
        services.AddSingleton<IHierarchyDepModel>(p => p.GetRequiredService<SingletonHierarchyDepModel>());
        services.AddTransient<TransientDepModel>();
    }
}
