// This file generated by DragoAnt.Extensions.DependencyInjection source generator.
// More details: https://github.com/DragoAnt/Extensions.DependencyInjection



#nullable enable

using DragoAnt.Extensions.DependencyInjection.Example.Models;
using Microsoft.Extensions.DependencyInjection;
using System;

[assembly:ResolveAssembly("TestAssembly.TestAssemblyDependencyExtensions.AddTestAssemblyDependencies")]

namespace TestAssembly;

/// <summary>
/// Dependency injection registration extensions.
/// </summary>
public static partial class TestAssemblyDependencyExtensions
{
    /// <summary>
    /// AddTestAssemblyDependencies dependencies and factories registration extension.
    /// </summary>
    /// <remarks>Generated by <a href="https://github.com/DragoAnt/Extensions.DependencyInjection">DragoAnt.Extensions.DependencyInjection</a> source generator.</remarks>
    public static void AddTestAssemblyDependencies(this IServiceCollection services)
    {
        services.AddSingleton<GenericInterfaceDepModel>();
        services.AddSingleton<BaseHierarchyDepModel>(p => p.GetRequiredService<GenericInterfaceDepModel>());
        services.AddSingleton<IHierarchyDepModel>(p => p.GetRequiredService<GenericInterfaceDepModel>());
        services.AddSingleton<IGenericInterfaceDepModel<int>>(p => p.GetRequiredService<GenericInterfaceDepModel>());
        services.AddSingleton<HierarchyDepModel>();
        services.AddSingleton<BaseHierarchyDepModel>(p => p.GetRequiredService<HierarchyDepModel>());
        services.AddSingleton<IHierarchyDepModel>(p => p.GetRequiredService<HierarchyDepModel>());
        services.AddScoped<ScopedDepModel>();
        services.AddSingleton<SingletonDepModel>();
        services.AddSingleton<SingletonHierarchyDepModel>();
        services.AddSingleton<BaseHierarchyDepModel>(p => p.GetRequiredService<SingletonHierarchyDepModel>());
        services.AddSingleton<IHierarchyDepModel>(p => p.GetRequiredService<SingletonHierarchyDepModel>());
    }

}
