// This file generated by DragoAnt.Extensions.DependencyInjection source generator.
// More details: https://github.com/DragoAnt/Extensions.DependencyInjection



#nullable enable

using DragoAnt.Extensions.DependencyInjection.Example.Models;
using Microsoft.Extensions.DependencyInjection;
using System;
using static Microsoft.Extensions.DependencyInjection.ServiceLifetime;

[assembly:ResolveAssembly("TestAssembly.TestAssemblyDependencyExtensions.AddTestAssemblyDependencies")]

namespace TestAssembly;

/// <summary>
/// Dependency injection registration extensions.
/// </summary>
public static partial class TestAssemblyDependencyExtensions
{
    /// <summary>
    /// AddTestAssemblyDependencies dependencies and factories registration extension.
    /// </summary>
    /// <remarks>Generated by <a href="https://github.com/DragoAnt/Extensions.DependencyInjection">DragoAnt.Extensions.DependencyInjection</a> source generator.</remarks>
    public static void AddTestAssemblyDependencies(this IServiceCollection services)
    {

        services.Add(new ServiceDescriptor(typeof(ISampleClassFactory), typeof(SampleClassFactory), Scoped));
    }

}

/// <summary>
/// Factory contract for <see cref="SampleClass"/>.
/// </summary>
public interface ISampleClassFactory
{
    SampleClass Create(string name, int age);
}

/// <summary>
/// Factory implementation for <see cref="SampleClass"/>.
/// </summary>
internal sealed class SampleClassFactory : ISampleClassFactory
{
    private readonly IServiceProvider _provider;

    public SampleClassFactory(IServiceProvider provider)
    {
        _provider = provider;        
    }

    SampleClass ISampleClassFactory.Create(string name, int age) 
         => new SampleClass(name, age);
}
