// This file generated by DragoAnt.Extensions.DependencyInjection.Factory source generator

#nullable enable

using DragoAnt.Extensions.DependencyInjection.Example.Models;
using Microsoft.Extensions.DependencyInjection;
using System;

namespace NotSetRootNamespace;

/// <summary>
/// Factory dependency injection registration extensions.
/// </summary>
public static class NotSetMethodNameRegistrationExtensions
{
    /// <summary>
    /// NotSetMethodName dependencies and factories registration extension.
    /// </summary>
    /// <remarks>Generated by <a href="https://github.com/DragoAnt/Extensions.DependencyInjection">DragoAnt.Extensions.DependencyInjection</a> source generator.</remarks>
    public static void AddNotSetMethodNameDependencies(this IServiceCollection services)
    {
        services.AddScoped<ISampleClassFactory, SampleClassFactory>();
    }
}

/// <summary>
/// Factory contract for <see cref="SampleClass"/>.
/// </summary>
public interface ISampleClassFactory
{
    SampleClass Create(string name, int age);
}

/// <summary>
/// Factory implementation for <see cref="SampleClass"/>.
/// </summary>
internal sealed class SampleClassFactory : ISampleClassFactory
{
    private readonly IServiceProvider _provider;

    public SampleClassFactory(IServiceProvider provider)
    {
        _provider = provider;        
    }

    SampleClass ISampleClassFactory.Create(string name, int age) =>
        new SampleClass(name, age);
}
