// This file generated by DragoAnt.Extensions.DependencyInjection source generator

using Microsoft.Extensions.DependencyInjection;

namespace TestAssembly;

internal static class ReferencedRegistrationExtensions
{
    /// <summary>
    /// Register all referenced dependencies.
    /// </summary>
    /// <remarks>Generated by <a href="https://github.com/DragoAnt/Extensions.DependencyInjection">DragoAnt.Extensions.DependencyInjection</a> source generator.</remarks>
    public static void AddReferencedDependencies(this IServiceCollection services)
    {
        DragoAnt.Extensions.DependencyInjection.Example.ExampleDependencyExtensions.AddExampleDependencies(services);
    }
}