// This file generated by DragoAnt.Extensions.DependencyInjection source generator.
// More details: https://github.com/DragoAnt/Extensions.DependencyInjection

using Microsoft.Extensions.DependencyInjection;

namespace TestAssembly;

internal static class ReferencedRegistrationExtensions
{
    /// <summary>
    /// Register all referenced dependencies.
    /// </summary>
    /// <remarks>Generated by <a href="https://github.com/DragoAnt/Extensions.DependencyInjection">DragoAnt.Extensions.DependencyInjection.Referenced</a> source generator.</remarks>
    public static void AddReferencedDependencies(this IServiceCollection services)
    {
        DragoAnt.Extensions.DependencyInjection.Example.ExampleDependencyExtensions.AddExampleDependencies(services);
    }

    /// <summary>
    /// Register all dependencies(referenced anf own).
    /// </summary>
    /// <remarks>Generated by <a href="https://github.com/DragoAnt/Extensions.DependencyInjection">DragoAnt.Extensions.DependencyInjection.Referenced</a> source generator.</remarks>
    public static void AddDependencies(this IServiceCollection services)
    {
        services.AddReferencedDependencies();
        TestAssembly.TestAssemblyDependencyExtensions.AddTestAssemblyDependencies(services);
    }
}